### ISSUE TITLE
ERROR: : Failed to load PyTorch native library

### ISSUE THREAD

**Issue by SahPet** [qupath/qupath-extension-wsinfer#33]
I'm getting a "Failed to load PyTorch native library" error. Seems like it's trying to use ...\.djl.ai\pytorch\1.13.0-cu117-win-x86_64\torch_cuda_cpp.dll. Also, GPU does not show up as an option on the Qupath WSInfer "Preferred device:". Any way to run this from a venv for example with better control over the torch/cuda versions being installed/utilized (however, I guess the installed torch/cuda version isn't relevant as all is fully run by the djl.ai\pytorch)? Haven't tried different versions of http://djl.ai/engines/pytorch/pytorch-engine/, but I this seems to be automatically installed/chosen by the extension or is that worth trying?

```
INFO: : Downloading PyTorch engine...
ERROR: Failed to load PyTorch native library
ai.djl.engine.EngineException: Failed to load PyTorch native library
    at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:85)
    at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
    at ai.djl.engine.Engine.getEngine(Engine.java:186)
    at qupath.ext.wsinfer.ui.PytorchManager.lambda$getEngineOnline$1(PytorchManager.java:90)
    at qupath.ext.wsinfer.ui.PytorchManager.callWithTempProperty(PytorchManager.java:124)
    at qupath.ext.wsinfer.ui.PytorchManager.callOnline(PytorchManager.java:116)
    at qupath.ext.wsinfer.ui.PytorchManager.getEngineOnline(PytorchManager.java:90)
    at qupath.ext.wsinfer.ui.WSInferController$WSInferTask.call(WSInferController.java:392)
    at qupath.ext.wsinfer.ui.WSInferController$WSInferTask.call(WSInferController.java:369)
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by C:\Users\IT-bruker\.djl.ai\pytorch\1.13.0-cu117-win-x86_64\torch_cuda_cpp.dll: Den angitte prosedyren ble ikke funnet        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:368)
        at ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:174)
        at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:78)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:54)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:186)
        at qupath.ext.wsinfer.ui.PytorchManager.lambda$getEngineOnline$1(PytorchManager.java:90)
        at qupath.ext.wsinfer.ui.PytorchManager.callWithTempProperty(PytorchManager.java:124)
        at qupath.ext.wsinfer.ui.PytorchManager.callOnline(PytorchManager.java:116)
        at qupath.ext.wsinfer.ui.PytorchManager.getEngineOnline(PytorchManager.java:90)
        at qupath.ext.wsinfer.ui.WSInferController$WSInferTask.call(WSInferController.java:392)
        at qupath.ext.wsinfer.ui.WSInferController$WSInferTask.call(WSInferController.java:369)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
WARN: Simple repository pointing to a non-archive file.
ERROR: : Failed to load PyTorch native library
```

**Comment by petebankhead** [comment]
> Any way to run this from a venv for example with better control over the torch/cuda versions being installed/utilized (however, I guess the installed torch/cuda version isn't relevant as all is fully run by the djl.ai\pytorch)?

The CUDA version matters, and has to be compatible with PyTorch 1.13.0 (or absent, in which case the CPU will be used).

All the management of PyTorch is handled by Deep Java LIbrary so there is not very much that can be controlled on the QuPath side.

There is a discussion on the forum that may be relevant: https://forum.image.sc/t/pytorch-initialization-issue-with-qupath-0-4-1/75563

The next QuPath release (tentatively planned for late September/early October) will update Deep Java Library... at which point the situation may be a bit different (or at least the required CUDA will probably differ).

**Comment by SahPet** [comment]
The error came when "CPU" as selected as device though, so cuda shouldn't matter really.

**Comment by petebankhead** [comment]
I'm using a Mac currently, so can't test it, but I think I've seen this behavior before: DJL picks up that CUDA is available, attempts to download the GPU version of PyTorch, and then fails to load either with or without GPU support because it turns out that the CUDA version is incompatible.

Unfortunately it isn't smart enough to figure this out in advance and download the CPU version of PyTorch.

The workaround I used was:

1. Delete the existing PyTorch installation from DJL - for you, I guess this is at `C:\Users\IT-bruker.djl.ai\pytorch\`
2. Delete CUDA, or install a compatible version (based upon [this](https://pytorch.org/get-started/previous-versions/) I think CUDA 11.6 or 11.7 should work)
3. Launch QuPath and the extension again, and allow DJL to automatically download PyTorch again

> Any way to run this from a venv for example with better control over the torch/cuda versions being installed/utilized

It *might* work if you install CUDA in a conda environment and [then launch QuPath via the command line](https://qupath.readthedocs.io/en/0.4/docs/advanced/command_line.html) from within that environment - although I don't know and I've never tested it.

The reason I hope it could work is that QuPath is definitely influenced by the conda environment when launched this way. I tested this with a Groovy script
```groovy
println System.env.entrySet().each {println it}
```
and I get different results when launched within a conda environment.

I don't know if that extends to helping DJL download the PyTorch version you want, but if you want to try it out I'd be really interested to know if it works. I understand relying exclusively on a specific CUDA version in a system-wide installation could be troublesome for a lot of people.

**Comment by kaczmarj** [comment]
@SahPet - could you please try again with v0.2.1 (https://github.com/qupath/qupath-extension-wsinfer/releases/tag/v0.2.1) ?

> I think CUDA 11.6 or 11.7 should work

yes, i am using qupath v0.4.4 on windows 11 with an 2080Ti gpu and confirm that cuda 11.7 works. you can download it at  https://developer.nvidia.com/cuda-11-7-0-download-archive
